# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    if: ${{ secrets.METRICS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Zhang-pchao
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_discussions: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 30
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_scholar: yes
          plugin_scholar_token: ${{ secrets.SCHOLAR_TOKEN }}
          plugin_scholar_fields: citations, hindex, i10index
          plugin_traffic: yes

          repositories: 100
          config_padding: 0, 8 + 15%
          filename: github-metrics.svg
