name: GitHub metrics

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  metrics:
    if: ${{ secrets.METRICS_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Zhang-pchao
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, editors, categories
          plugin_repositories: 100
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 2
          plugin_scholar: yes
          plugin_scholar_token: ${{ secrets.SCHOLAR_TOKEN }}
          plugin_scholar_fields: citations, hindex, i10index
          filename: github-metrics.svg
